export const ROUTE_REQUEST = "ROUTE_REQUEST";
export const ROUTE_FAILURE = "ROUTE_FAILURE";
export const ROUTE_SUCCESS = "ROUTE_SUCCESS";

export const GET_ROUTE_REQUEST = "GET_ROUTE_REQUEST";
export const GET_ROUTE_FAILURE = "GET_ROUTE_FAILURE";
export const GET_ROUTE_SUCCESS = "GET_ROUTE_SUCCESS";

export const TOGGLE_IS_ROUTE = "TOGGLE_IS_ROUTE";
export const RESET_ROUTE = "RESET_ROUTE";
