export const AUTH_USER_REQUEST = "AUTH_USER_REQUEST";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
